#pragma once

#define __CTL_THREAD_API_FLAG_PTHREAD (1 << 0)
#define __CTL_THREAD_API_FLAG_NONE (1 << 1)
#define __CTL_THREAD_API_FLAG_LAST_BIT 1

#define __CTL_THREAD_API_PTHREAD ((1 << (__CTL_THREAD_API_FLAG_LAST_BIT+1))|__CTL_THREAD_API_FLAG_PTHREAD)
#define __CTL_THREAD_API_GTHREAD_PTHREAD ((1 << (__CTL_THREAD_API_FLAG_LAST_BIT+2))|__CTL_THREAD_API_FLAG_PTHREAD)
#define __CTL_THREAD_API_GTHREAD_NONE ((1 << (__CTL_THREAD_API_FLAG_LAST_BIT+3))|__CTL_THREAD_API_FLAG_NONE)
#define __CTL_THREAD_API_C11 (1 << (__CTL_THREAD_API_FLAG_LAST_BIT+4))
#define __CTL_THREAD_API_EXTERNAL (1 << (__CTL_THREAD_API_FLAG_LAST_BIT+5))
#define __CTL_THREAD_API_WINDOWS (1 << (__CTL_THREAD_API_FLAG_LAST_BIT+6))
#define __CTL_THREAD_API_NONE ((1 << (__CTL_THREAD_API_FLAG_LAST_BIT+7))|__CTL_THREAD_API_FLAG_NONE)

#if CTL_LIBCPP == CTL_LIBCPP_LIBCPP
	#ifdef _LIBCPP_HAS_THREAD_API_PTHREAD
		#define __CTL_THREAD_API __CTL_THREAD_API_PTHREAD
	#elif defined _LIBCPP_HAS_THREAD_API_C11
		#define __CTL_THREAD_API __CTL_THREAD_API_C11
	#elif defined _LIBCPP_HAS_THREAD_API_EXTERNAL
		#define __CTL_THREAD_API __CTL_THREAD_API_EXTERNAL
	#elif defined _LIBCPP_HAS_THREAD_API_WIN32
		#define __CTL_THREAD_API __CTL_THREAD_API_WINDOWS
	#elif defined _LIBCPP_HAS_NO_THREADS
		#define __CTL_THREAD_API __CTL_THREAD_API_NONE
	#else
		#error
	#endif
#elif CTL_LIBCPP == CTL_LIBCPP_GLIBCXX
	#ifdef _GLIBCXX_HAS_GTHREADS
		#include <bits/gthr-default.h>

		#ifdef _GLIBCXX_GCC_GTHR_POSIX_H
			#define __CTL_THREAD_API __CTL_THREAD_API_GTHREAD_PTHREAD
		#elif defined _GLIBCXX_GCC_GTHR_SINGLE_H
			#define __CTL_THREAD_API __CTL_THREAD_API_GTHREAD_NONE
		#else
			#error
		#endif
	#else
		#define __CTL_THREAD_API __CTL_THREAD_API_NONE
	#endif
#else
	#error
#endif
