#define CTL_ARCHITECTURE_FLAG_32BITS (1 << 0)
#define CTL_ARCHITECTURE_FLAG_64BITS (1 << 1)
#define CTL_ARCHITECTURE_FLAG_X86 (1 << 2)
#define CTL_ARCHITECTURE_FLAG_WASM (1 << 3)

#define CTL_ARCHITECTURE_X86 (CTL_ARCHITECTURE_FLAG_X86|CTL_ARCHITECTURE_FLAG_32BITS)
#define CTL_ARCHITECTURE_X86_64 (CTL_ARCHITECTURE_FLAG_X86|CTL_ARCHITECTURE_FLAG_64BITS)
#define CTL_ARCHITECTURE_WASM_32 (CTL_ARCHITECTURE_FLAG_WASM|CTL_ARCHITECTURE_FLAG_32BITS)
#define CTL_ARCHITECTURE_WASM_64 (CTL_ARCHITECTURE_FLAG_WASM|CTL_ARCHITECTURE_FLAG_64BITS)

#if defined __x86_64__ || \
	defined _M_IA64 || \
	defined _WIN64 || \
	defined __MINGW64__
	#define CTL_TARGET_ARCHITECTURE CTL_ARCHITECTURE_X86_64
#elif defined __i386__ || \
		defined _M_IX86 || \
		defined _WIN32 || \
		defined __MINGW32__
	#define CTL_TARGET_ARCHITECTURE CTL_ARCHITECTURE_X86
#elif defined __wasm32__
	#define CTL_TARGET_ARCHITECTURE CTL_ARCHITECTURE_WASM_32
#elif defined __wasm64__
	#define CTL_TARGET_ARCHITECTURE CTL_ARCHITECTURE_WASM_64
#else
	#error
#endif
