#define CTL_LIBCPP_FLAG_GNU (1 << 0)
#define __CTL_LIBCPP_FLAGS_LAST_BIT 0

#define CTL_LIBCPP_GLIBCXX ((1 << (__CTL_LIBCPP_FLAGS_LAST_BIT+1))|CTL_LIBCPP_FLAG_GNU)
#define CTL_LIBCPP_LIBCPP ((1 << (__CTL_LIBCPP_FLAGS_LAST_BIT+2))|CTL_LIBCPP_FLAG_GNU)

#ifdef _LIBCPP_VERSION
	#define CTL_LIBCPP CTL_LIBCPP_LIBCPP
#elif defined __GLIBCXX__ || defined __GLIBCPP__
	#define CTL_LIBCPP CTL_LIBCPP_GLIBCXX
#elif defined __CPPCHECK__
	#define CTL_LIBCPP CTL_LIBCPP_GLIBCXX
#else
	#error
#endif

#if CTL_LIBCPP == CTL_LIBCPP_GLIBCXX
	#if defined _GLIBCXX_CONCEPT_CHECKS || defined _GLIBCPP_CONCEPT_CHECKS
		#define __CTL_GLIBCXX_CONCEPT_CHECKS
	#endif
#endif
