#define CTL_LIBC_FLAG_POSIX (1 << 0)
#define CTL_LIBC_FLAG_GNU (1 << 1)
#define __CTL_LIBC_FLAGS_LAST_BIT 1

#define CTL_LIBC_GLIBC ((1 << (__CTL_LIBC_FLAGS_LAST_BIT+1))|CTL_LIBC_FLAG_POSIX|CTL_LIBC_FLAG_GNU)
#define CTL_LIBC_MUSL ((1 << (__CTL_LIBC_FLAGS_LAST_BIT+2))|CTL_LIBC_FLAG_POSIX|CTL_LIBC_FLAG_GNU)
#define CTL_LIBC_CRT (1 << (__CTL_LIBC_FLAGS_LAST_BIT+3))

#ifdef _WIN32_C_LIB
	#define CTL_LIBC CTL_LIBC_CRT
#elif defined _LIBCPP_HAS_MUSL_LIBC || defined __MUSL__
	#define CTL_LIBC CTL_LIBC_MUSL
#elif defined __GLIBC__
	#define CTL_LIBC CTL_LIBC_GLIBC
#else
	#error
#endif
