#define CTL_KERNEL_FLAG_UNIX (1 << 0)
#define __CTL_KERNEL_FLAGS_LAST_BIT 1

#define CTL_KERNEL_LINUX ((1 << (__CTL_KERNEL_FLAGS_LAST_BIT+1))|CTL_KERNEL_FLAG_UNIX)
#define CTL_KERNEL_WINDOWS (1 << (__CTL_KERNEL_FLAGS_LAST_BIT+2))
#define CTL_KERNEL_EMSCRIPTEN (1 << (__CTL_KERNEL_FLAGS_LAST_BIT+3))

#define CTL_OS_FLAG_POSIX (1 << 0)
#define CTL_OS_FLAG_UNIX (1 << 1)
#define CTL_OS_FLAG_WINDOWS (1 << 2)
#define __CTL_OS_FLAGS_LAST_BIT 2

#define CTL_OS_GNU ((1 << (__CTL_OS_FLAGS_LAST_BIT+1))|CTL_OS_FLAG_POSIX|CTL_OS_FLAG_UNIX)
#define CTL_OS_ANDROID ((1 << (__CTL_OS_FLAGS_LAST_BIT+2))|CTL_OS_FLAG_POSIX|CTL_OS_FLAG_UNIX)
#define CTL_OS_WINDOWS ((1 << (__CTL_OS_FLAGS_LAST_BIT+3))|CTL_OS_FLAG_WINDOWS)
#define CTL_OS_CYGWIN ((1 << (__CTL_OS_FLAGS_LAST_BIT+4))|CTL_OS_FLAG_WINDOWS|CTL_OS_FLAG_POSIX|CTL_OS_FLAG_UNIX)
#define CTL_OS_WASI ((1 << (__CTL_OS_FLAGS_LAST_BIT+5))|CTL_OS_FLAG_POSIX|CTL_OS_FLAG_UNIX)

#if defined __linux__ || \
		defined linux || \
		defined __linux || \
		defined __gnu_linux__
	#define CTL_TARGET_KERNEL CTL_KERNEL_LINUX
#elif defined _WIN32 || \
	defined _WIN64 || \
	defined __WIN32__ || \
	defined __WINDOWS__ || \
	defined __TOS_WIN__
	#define CTL_TARGET_KERNEL CTL_KERNEL_WINDOWS
#elif defined __EMSCRIPTEN__
	#define CTL_TARGET_KERNEL CTL_KERNEL_EMSCRIPTEN
#else
	#error
#endif

#ifdef __ANDROID__
	#define CTL_TARGET_OS CTL_OS_ANDROID
#elif defined __CYGWIN__
	#define CTL_TARGET_OS CTL_OS_CYGWIN
#elif defined __GNU__ || \
		defined __gnu_linux__
	#define CTL_TARGET_OS CTL_OS_GNU
#elif CTL_TARGET_KERNEL == CTL_KERNEL_WINDOWS
	#define CTL_TARGET_OS CTL_OS_WINDOWS
#elif defined __EMSCRIPTEN__
	#define CTL_TARGET_OS CTL_OS_WASI
#else
	#error
#endif

#define CTL_PLATFORM_DESKTOP 0
#define CTL_PLATFORM_MOBILE 1
#define CTL_PLATFORM_WEB 2

#if CTL_TARGET_OS == CTL_OS_ANDROID
	#define CTL_TARGET_PLATFORM CTL_PLATFORM_MOBILE
#elif CTL_TARGET_OS == CTL_OS_GNU || \
		CTL_TARGET_OS == CTL_OS_WINDOWS || \
		CTL_TARGET_OS == CTL_OS_CYGWIN
	#define CTL_TARGET_PLATFORM CTL_PLATFORM_DESKTOP
#elif CTL_TARGET_KERNEL == CTL_KERNEL_EMSCRIPTEN || \
		CTL_TARGET_OS == CTL_OS_WASI
	#define CTL_TARGET_PLATFORM CTL_PLATFORM_WEB
#else
	#error
#endif
