#pragma once

#define CPA_ARCHITECTURE_FLAG_32BITS (1 << 0)
#define CPA_ARCHITECTURE_FLAG_64BITS (1 << 1)
#define CPA_ARCHITECTURE_FLAG_X86    (1 << 2)
#define CPA_ARCHITECTURE_FLAG_WASM   (1 << 3)

#define CPA_ARCHITECTURE_X86 (CPA_ARCHITECTURE_FLAG_X86|CPA_ARCHITECTURE_FLAG_32BITS)
#define CPA_ARCHITECTURE_X86_64 (CPA_ARCHITECTURE_FLAG_X86|CPA_ARCHITECTURE_FLAG_64BITS)
#define CPA_ARCHITECTURE_WASM_32 (CPA_ARCHITECTURE_FLAG_WASM|CPA_ARCHITECTURE_FLAG_32BITS)
#define CPA_ARCHITECTURE_WASM_64 (CPA_ARCHITECTURE_FLAG_WASM|CPA_ARCHITECTURE_FLAG_64BITS)

#if defined __x86_64__ || defined _M_IA64
	#define CPA_TARGET_ARCHITECTURE CPA_ARCHITECTURE_X86_64
#elif defined __i386__ || defined _M_IX86
	#define CPA_TARGET_ARCHITECTURE CPA_ARCHITECTURE_X86
#elif defined __wasm64__
	#define CPA_TARGET_ARCHITECTURE CPA_ARCHITECTURE_WASM_64
#elif defined __wasm32__
	#define CPA_TARGET_ARCHITECTURE CPA_ARCHITECTURE_WASM_32
#else
	#error
#endif
