#pragma once

#include "kernels.h"
#include "os.h"

#define CPA_PLATFORM_DESKTOP 0
#define CPA_PLATFORM_MOBILE  1
#define CPA_PLATFORM_WEB     2

#if CPA_TARGET_OS == CPA_OS_ANDROID
	#define CPA_TARGET_PLATFORM CPA_PLATFORM_MOBILE
#elif CPA_TARGET_KERNEL == CPA_KERNEL_EMSCRIPTEN
	#define CPA_TARGET_PLATFORM CPA_PLATFORM_WEB
#else
	#define CPA_TARGET_PLATFORM CPA_PLATFORM_DESKTOP
#endif
